server {
    listen 80;
    listen [::]:80;
    server_name bitcoin.seedframe.xyz;

    location ^~ /.well-known/acme-challenge/ {
        root /data/btcpay/acme;
        default_type text/plain;
        try_files $uri =404;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}
